#!/bin/bash

_todo_complete() {
	local cur prev opts
	COMPREPLY=()
	cur="${COMP_WORDS[COMP_CWORD]}"
	prev="${COMP_WORDS[COMP_CWORD - 1]}"
	opts="-a --add -u --update -d --delete -f --finish -l --list -s --start -e --detail -v --version"

	if [[ ${cur} == -* ]]; then
		# Handle options
		COMPREPLY=($(compgen -W "$opts" -- $cur))
	elif [[ ${prev} == -d || ${prev} == -f || ${prev} == -s || ${prev} == -e ]]; then
		# Handle task ID suggestions for delete, finish, start, and detail commands
		task_ids=$(todo --list --all | awk '{print $2}') # This assumes task IDs are the second column
		COMPREPLY=($(compgen -W "$task_ids" -- $cur))
	fi
}

complete -F _todo_complete todo
