# Manpage for todo
.TH TODO 1 "November 2024" "v1.0.9" "User Commands"
.SH NAME
todo \- A simple command-line to-do list manager
.SH SYNOPSIS
.B todo
[\fIcommand\fR] [\fIoptions\fR]
.SH DESCRIPTION
The \fItodo\fR command is a command-line to-do list manager that allows users to manage their tasks with the following features:
- Add, update, and delete tasks.
- List tasks by their status.
- Mark tasks as finished or start working on them.
- View task details and more.

.SH COMMANDS
.TP
.B -a, --add
Add a new task.
.TP
.B -u, --update
Update an existing task.
.TP
.B -d, --delete <id>
Delete a task by ID.
.TP
.B -f, --finish <id>
Mark a task as done by ID.
.TP
.B -l, --list [status]
List all tasks, or filter by a specific status: "todo", "in-progress", "done", or "all" (default).
.TP
.B -s, --start <id>
Start working on a task.
.TP
.B -e, --detail <id>
View details of a task.
.TP
.B -v, --version
View the version number of the todo CLI.

.SH OPTIONS
.TP
.B <status>
Specifies the status of the tasks to list. Can be "todo", "in-progress", "done", or "all" (default).
.TP
.B <id>
The ID of the task to update, delete, finish, or start.

.SH EXAMPLES
.TP
Add a task:
.nf
todo -a
.nf
.TP
Update a task:
.nf
todo -u <task_id>
.nf
.TP
List tasks by status:
.nf
todo -l "todo"
.nf
.TP
Delete a task:
.nf
todo -d <task_id>
.nf
.TP
Finish a task:
.nf
todo -f <task_id>
.nf

.SH AUTHOR
Caesar003, <https://github.com/caesar003/todo.git>
